### ISSUE TITLE
Unable to build on Mac OS Mojave

### ISSUE THREAD

**Issue by Trent54** [libyal/libcaes#14]
I got this error when trying to build libfsapfs with "make." I decided to try to build and install libcaes separately, but I get the same error. My goal is to build libfsapfs.

**Comment by Trent54** [comment]
Oops, forgot to attach output of make
<img width="566" alt="libcaes error" src="https://user-images.githubusercontent.com/44457556/88122967-c20a6380-cb7e-11ea-8149-fad9644c1e36.png">

**Comment by joachimmetz** [comment]
how did you get the source via git or from the [source distribution package](https://github.com/libyal/libcaes/wiki/Building#source-distribution-package) ?

**Comment by Trent54** [comment]
Hi Joachim, thank you for getting back to me. I got it from Git but when I run ./synclibs.sh, per the instructions here:



 I get the following error:

**Comment by joachimmetz** [comment]
@Trent54 it looks like your previous message did not contain all the data, don't use the reply via email option it has limitations.

You are running the development version as explained here https://github.com/libyal/libcaes/wiki/Building#read-first
If you're not developing libcaes or libfsapfs, then I opt to not use this version.

(I repeat) can you attach your config.log

**Comment by Trent54** [comment]
It is attached. Thank you again!

**Comment by joachimmetz** [comment]
> It is attached. Thank you again!

It is not, since you did use reply via email again

Per the github reply **"it looks like your previous message did not contain all the data, don't use the reply via email option it has limitations."**

**Comment by Trent54** [comment]
I understand now, sorry - reply via Github incoming

**Comment by Trent54** [comment]
[config.log](https://github.com/libyal/libcaes/files/4958291/config.log)

**Comment by joachimmetz** [comment]
https://github.com/libyal/libcaes/blob/8fe8e461a60fe45c495ec1410a9afc55b6ab0079/libcaes/libcaes_context.c#L324
```
#elif defined( HAVE_LIBCRYPTO ) && defined( HAVE_OPENSSL_EVP_H ) && ( defined( HAVE_EVP_CRYPTO_AES_CBC ) || defined( HAVE_EVP_CRYPTO_AES_ECB ) )
```

Per config.log
```
| #define HAVE_OPENSSL_EVP_H 1
| #define HAVE_LIBCRYPTO 1
| #define HAVE_OPENSSL_AES_H 1
...
ac_cv_libcrypto=yes
ac_cv_libcrypto_CPPFLAGS=-I/opt/local/include
ac_cv_libcrypto_LIBADD=-lcrypto
ac_cv_libcrypto_aes=no
ac_cv_libcrypto_aes_cbc=no
ac_cv_libcrypto_aes_ecb=no
ac_cv_libcrypto_aes_xts=no
ac_cv_libcrypto_dummy=no
ac_cv_libcrypto_evp=yes
ac_cv_libcrypto_evp_cipher=no
```

But the following are missing:
```
HAVE_AES_CBC_ENCRYPT
HAVE_AES_ECB_ENCRYPT
HAVE_EVP_CRYPTO_AES_CBC
HAVE_EVP_CRYPTO_AES_ECB
```

So `LIBCAES_HAVE_AES_SUPPORT` is not set in https://github.com/libyal/libcaes/blob/0459d83c6d10a35fa274bc5c3c6f3458e45e51d3/libcaes/libcaes_definitions.h.in#L56 since both `HAVE_LIBCRYPTO` and `HAVE_OPENSSL_EVP_H` are set but your OpenSSL build does not appear to have the EVP Cypher functions.

I'll have a look to change m4/libcrypto.m4 to account for this case in the mean time run configure with `--with-openssl=no` to disable OpenSSL support.

**Comment by Trent54** [comment]
Awesome, I'll give it a try now. Thank you!

**Comment by joachimmetz** [comment]
Or this might be related to your build environment not properly configured:
```
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Try setting:
```
export CFLAGS="-I/usr/local/include -I/usr/local/opt/openssl@1.1/include ${CFLAGS}";
export LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib ${LDFLAGS}";
```

before running `./configure`

**Comment by Trent54** [comment]
Hmmm...

Was getting another error with before (see below) but will try that way
<img width="566" alt="image" src="https://user-images.githubusercontent.com/44457556/88146275-825c6f80-cbb0-11ea-83d5-d5218f9ae205.png">

**Comment by Trent54** [comment]
Still same error after setting CFLAGS & LDFLAGS per above.
<img width="566" alt="image" src="https://user-images.githubusercontent.com/44457556/88146528-dbc49e80-cbb0-11ea-8fd4-442eb683c595.png">

**Comment by joachimmetz** [comment]
You'll need to run `./synclibs.sh` and `./autogen.sh` as indicated here https://github.com/libyal/libcaes/wiki/Building#git

I repeat using the source from git is **NOT** recommended if you're not developing libcaes.

**Comment by Trent54** [comment]
Here is an ls of my libcerror directory 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/44457556/88146651-fd258a80-cbb0-11ea-983d-4be93c317d04.png">

**Comment by Trent54** [comment]
I tried following directions, really :) I did that but had an error. 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/44457556/88146759-1e867680-cbb1-11ea-8c3a-0d4e50fc5481.png">

**Comment by Trent54** [comment]
This error:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/44457556/88146883-4fff4200-cbb1-11ea-86c7-7555132e6925.png">

**Comment by joachimmetz** [comment]
Why is that an error?

**Comment by Trent54** [comment]
It isn't?

**Comment by Trent54** [comment]
I thought it was because reinstalling libcaes didn't fix the original problem. (attached). 

![](https://user-images.githubusercontent.com/44457556/88122967-c20a6380-cb7e-11ea-8149-fad9644c1e36.png)

**Comment by Trent54** [comment]
I also installed liberror separately - I'm guessing I shouldn't have done that because there is a libcerror directory inside libcaes and one in the git directory

<img width="575" alt="image" src="https://user-images.githubusercontent.com/44457556/88147577-432f1e00-cbb2-11ea-8098-5665d323e6a0.png">

**Comment by joachimmetz** [comment]
You are not listening to my advise nor are you following the instructions that have been written to prevent people falling in to the trap of trying to use the version that is intended for development.

1. Stop using the source from git directly.
2. Use https://github.com/libyal/libfsapfs/releases/download/20200416/libfsapfs-experimental-20200416.tar.gz

It has all the dependencies included. Use `--with-openssl=no` or make sure to set up CFLAGS & LDFLAGS as indicated before.

**Comment by Trent54** [comment]
I am sorry, I am new to using git.

**Comment by Trent54** [comment]
I will build from inside the .tar.gz which I have downloaded. I didn't understand which part of your directions applied to what. I remember I started with Mac OS build from package, then after that failed I found the build from source directions.

**Comment by Trent54** [comment]
I see now. This is more to my unfamiliarity with git I think. I found an article about libfsapfs, searched and found the project on git, clicked documentation and clicked "build from source." I actually thought that's all anyone could use GitHub for and did not understand the concept of separate releases. 

I don't mean to imply the documentation does not make this clear. Thank you again for all your help.

<img width="432" alt="image" src="https://user-images.githubusercontent.com/44457556/88148986-475c3b00-cbb4-11ea-9553-48423f26042e.png">
