### ISSUE TITLE
libcrypto EVP XTS functions available but not used?

### ISSUE THREAD

**Issue by jengelh** [libyal/libcaes#15]
```
libcaes» ./autogen.sh && ./configure
[...]
configure:
Building:
   libcerror support:       yes
   AES-CBC support:         libcrypto
   AES-ECB support:         libcrypto
   AES-XTS support:         local
```

But my libcrypto.so _does_ have the two functions for XTS:

```
» nm -D libcrypto.so.1.1
0000000000165370 T EVP_aes_128_xts
0000000000165390 T EVP_aes_256_xts
```

`acinclude.m4` has this to say:

```
  AS_IF(
    [test "x$ac_cv_libcrypto" != xno],
    [AX_LIBCRYPTO_CHECK_AES
    AX_LIBCRYPTO_CHECK_AES_XTS])
```

This means it only ever checks for set(CBC, EBC) _or_ set(XTS), but never both. Is this really intentional?

**Comment by joachimmetz** [comment]
Can you check your config.log (or attach it). 

There are more reasons why the OpenSSL EVP XTS functions are not enabled e.g. 
https://github.com/libyal/libcaes/blob/main/m4/libcrypto.m4#L21

**Comment by jengelh** [comment]
configure does not even print `checking for if `EVP_CipherInit_ex' can be used with duplicate keys`, which is a direct result of `AX_LIBCRYPTO_CHECK_AES_XTS` not getting invoked in the first place.

**Comment by joachimmetz** [comment]
Changes similar to proposed ones integrated in https://github.com/libyal/libcaes/commit/30c5241b77bfd366b80ad167aee15d917abd3389, closing issue.
