### ISSUE TITLE
Unable to override python interpreter

### ISSUE THREAD

**Issue by jengelh** [libyal/libcaes#19]
```
PYTHON_VERSION=3.9 PYTHON=python3.9 PYTHON_CONFIG=python3.9-config ./configure PYTHON_VERSION=3.9 PYTHON=python3.9 PYTHON_CONFIG=python3.9-config --enable-python3
[...]
Features:
   Python (pycaes) support: 3.8
```
It seems to be stuck with /usr/bin/python3-config and I cannot find a way to make it use a pythonX.Y-config of my choosing.

**Comment by joachimmetz** [comment]
@jengelh can you explain more what you're trying to accomplish and your configuration. Did you try a combination of `--with-pyprefix=no` and `--with-pythondir3` ?

**Comment by joachimmetz** [comment]
Ah in that case try e.g. `PYTHON_VERSION=3.8 ./configure --enable-python`
