### ISSUE TITLE
AES CCM implementation seems to different / non-compliant than others

### ISSUE THREAD

**Issue by kholia** [libyal/libcaes#2]
The AES CCM decryption results generated by `libcaes` are different than that generated by PolarSSL, OpenSSL and SJCL. https://github.com/ARMmbed/mbedtls/blob/master/library/ccm.c has some AES CCM decryption test vectors which aren't handled correctly by `libcaes`.

Is this by design, perhaps to conform to some platform specific AES CCM implementations? Or am I doing something wrong?

Here is a test-case to demonstrate this,

```
$ cat ccm_tester.py 
#!/usr/bin/env python

import sys
import pycaes
from binascii import hexlify


def pycaes_test_crypt_ccm(mode, key, nonce, input_data, expected_output_data):
    caes_context = pycaes.context()
    caes_context.set_key(pycaes.crypt_modes.ENCRYPT, key)

    output_data = pycaes.crypt_ccm(caes_context, mode, nonce, input_data)

    print("")
    print("actual output", hexlify(output_data))
    print("expected", hexlify(expected_output_data))

    return output_data == expected_output_data


def main():
    # NIST SP800-38C compliant test vector borrowed from the following link,
    # https://github.com/ARMmbed/mbedtls/blob/master/library/ccm.c
    key = [0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a,
           0x4b, 0x4c, 0x4d, 0x4e, 0x4f]
    nonce = [0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16]
    cipher_text = [0x71, 0x62, 0x01, 0x5b]
    plain_text = [0x20, 0x21, 0x22, 0x23]

    print("Testing AES-CCM 128-bit decryption\t"),

    test_key = bytes(bytearray(key))
    test_nonce = bytes(bytearray(nonce))
    test_cipher_text = bytes(bytearray(cipher_text))
    test_plain_text = bytes(bytearray(plain_text))

    result = pycaes_test_crypt_ccm(pycaes.crypt_modes.DECRYPT, test_key,
                                   test_nonce, test_cipher_text,
                                   test_plain_text)

    if not result:
        print("(FAIL)")
    else:
        print("(PASS)")


if __name__ == "__main__":
    if not main():
        sys.exit(1)
    else:
        sys.exit(0)
```

Running this results in,

```
Testing AES-CCM 128-bit decryption
('actual output', '5c4a101d')
('expected', '20212223')
(FAIL)
```

**Comment by kholia** [comment]
I "solved" this problem by copying the `libcaes` implementation of AES CCM to my code base.

I am writing a John the Ripper jumbo plugin to brute-force password protected BitLocker volumes. My project is heavily based on your `libbde` project :-)

I think that this issue can be closed now.

**Comment by joachimmetz** [comment]
> I "solved" this problem by copying the libcaes implementation of AES CCM to my code base.

FYI you cannot copy the code without adopting the LPGLv3 license.
Either use it as a library or make your project LPGLv3.

**Comment by joachimmetz** [comment]
I'll have a look at your initial report as soon as time permits, libcaes is large intended for fallback purposes using system native crypto libraries are highly recommended because of performance and crypto security.

**Comment by kholia** [comment]
I can't use `libcaes` as a library. Hence, I chose to copy the AES CCM implementation.

https://github.com/kholia/JohnTheRipper/tree/BitLocker (top commit) mentions the origin and license of the function that I copied from `libcaes`. 

https://github.com/kholia/JohnTheRipper/blob/BitLocker/src/aes_ccm_plug.c is the file where the borrowed function resides. I can re-write the borrowed implementation (it already has gone substantial change) if you think that combining existing GPLv2 code with borrowed LGPLv3 code in a single file is a problem.

Thanks!

**Comment by joachimmetz** [comment]
> tif you think that combining existing GPLv2 code with borrowed LGPLv3 code in a single file is a problem.

Short answer I'm not a laywer ;) slightly longer answer it's a mess: http://gplv3.fsf.org/wiki/index.php/Compatible_licenses#GPLv2-incompatible_licenses

My understanding of the matter, if you are including GPLv2 as open source your entire project should be GPLv2 or include GPLv2 compatible code. You should not combine code of different licenses in the same file, this I think violates the licence and the copyright of the original file.

**Comment by kholia** [comment]
OK, thanks! :-)

I will try to re-implement the borrowed GPL / LGPL code under a less restrictive license. That should make everyone happy.

**Comment by joachimmetz** [comment]
Therefore I provide the code as a library, no need to re-implement the code, just use the library. LGPL largely only restrictive if you copy it outside its codebase.
