### ISSUE TITLE
test script for "types" is missing

### ISSUE THREAD

**Issue by themaddoctor** [libyal/libcaes#8]
test script for "types" is missing

**Comment by joachimmetz** [comment]
What do you mean? Could you be more specific what error you are getting.

**Comment by themaddoctor** [comment]
make[3]: *** No rule to make target 'test_api_types.sh', needed by
'test_api_types.sh.log'.  St
op.
make[3]: Leaving directory '/building/testdisk/libcaes-20170110/tests'
make[2]: *** [Makefile:1079: check-TESTS] Error 2
make[2]: Leaving directory '/building/testdisk/libcaes-20170110/tests'
make[1]: *** [Makefile:1164: check-am] Error 2
make[1]: Leaving directory '/building/testdisk/libcaes-20170110/tests'
make: *** [Makefile:605: check-recursive] Error 1


On 1/29/18, Joachim Metz <notifications@github.com> wrote:
> What do you mean? Could you be more specific what error you are getting.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/libyal/libcaes/issues/8#issuecomment-361150461


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by joachimmetz** [comment]
I see in the released version. In the current source test_api_types.sh has been replaced by test_library.sh and test_library.ps1 I'll prep a new release.

**Comment by joachimmetz** [comment]
Give https://github.com/libyal/libcaes/releases/tag/20180108 a try

**Comment by themaddoctor** [comment]
OK, I will.

And, I know it's another question altogether, but what advantage would
--enable-wide-char-type add, if any?


On 1/29/18, Joachim Metz <notifications@github.com> wrote:
> Give https://github.com/libyal/libcaes/releases/tag/20180108 a try
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/libyal/libcaes/issues/8#issuecomment-361154082


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by joachimmetz** [comment]
> And, I know it's another question altogether, but what advantage would --enable-wide-char-type add, if any?

Which platforms? Are cross compiling?

**Comment by themaddoctor** [comment]
Linux 64, not cross-compiling.


On 1/29/18, Joachim Metz <notifications@github.com> wrote:
>> And, I know it's another question altogether, but what advantage would
>> --enable-wide-char-type add, if any?
>
> Which platforms? Are cross compiling?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/libyal/libcaes/issues/8#issuecomment-361157721


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by joachimmetz** [comment]
Since narrow character `char` supports Unicode (UTF-8) there is not much added value using `--enable-wide-char-type` on Linux unless you really need `wchar_t` support by any of the the dependencies.

**Comment by themaddoctor** [comment]
thanks


On 1/29/18, Joachim Metz <notifications@github.com> wrote:
> Since narrow character `char` supports Unicode (UTF-8) there is not much
> added value using `--enable-wide-char-type` on Linux unless you really need
> `wchar_t` support by any of the the dependencies.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/libyal/libcaes/issues/8#issuecomment-361158099


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by themaddoctor** [comment]
New release passes test, but it looks like what you did was remove any reference to test_api_types.sh.

**Comment by joachimmetz** [comment]
`test_api_types.sh` was replaced by `test_library.sh` https://github.com/libyal/libcaes/blob/master/tests/test_library.sh
